- name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script_stop: true # Ndalohet nëse ka gabim
          script: |
    # komandat e tua këtu
            cd /root/app_shitjet
            git pull origin main
            
            # 1. Vrit procesin e vjetër (nëse ekziston) për të pastruar memorien
            sudo pkill -9 streamlit || true
            
            # 2. Instalo varësitë e reja (nëse ke shtuar ndonjë te requirements.txt)
            pip install -r requirements.txt || echo "S'ka requirements"
            
            # 3. Nise Streamlit në background me nohup
            # Përdorim portën 8501 siç e kemi pasur
            nohup python3 -m streamlit run app.py --server.port 8501 --server.runOnSave true > streamlit.log 2>&1 &
            
            echo "Deployment i suksesshëm dhe Streamlit u rinis!"
