name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            cd /root/app_iphone_shitjet
            git pull origin main
            
            # Vrit proceset e vjetra
            sudo pkill -9 streamlit || true
            sudo pkill -9 python3 || true
            
            # Nise Streamlit pastër (përdorim rrugën që punoi më parë)
            nohup python3 -m streamlit run app.py --server.port 8501 --server.address 0.0.0.0 --server.runOnSave true > streamlit.log 2>&1 &
            
            echo "Deployment i suksesshëm!"